const test=require('node:test');const assert=require('node:assert/strict');
const fs=require('fs'),os=require('os'),path=require('path'),express=require('express'),sqlite3=require('sqlite3').verbose();
const migration=require('../migrations/001_create_visits_schema'),contactScopeMigration=require('../migrations/002_scope_company_contacts_by_department'),visits=require('../routes/visits'),validations=require('../routes/visit-validations');
let db,server,baseUrl,tempDir,visit,tokens={},messages=[];
const exec=sql=>new Promise((resolve,reject)=>db.exec(sql,error=>error?reject(error):resolve()));
const get=(sql,params=[])=>new Promise((resolve,reject)=>db.get(sql,params,(error,row)=>error?reject(error):resolve(row)));
async function request(method,url,body,headers={}){const response=await fetch(baseUrl+url,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...headers},body:body?JSON.stringify(body):undefined});return{status:response.status,body:await response.json()}}
const tokenFrom=result=>{
  for(const key of ['validation_url','token','token_hash','token_hint'])assert.equal(result.body[key],undefined);
  return decodeURIComponent(new URL(messages.at(-1).text.match(/https?:\/\/\S+/)[0]).pathname.split('/').pop());
};

test('fluxo público sem sessão expõe detalhes e confirma somente com aceite e nome registrado',async()=>{
  const created=await request('POST','/api/visits',{company_id:1,technician_id:1,department_ids:[1]});
  const id=created.body.id,item=created.body.departments[0];
  await request('POST','/api/visits/'+id+'/start');
  await request('PUT','/api/visits/'+id+'/departments/'+item.id,{demand_status:'com_demanda',activities:'Atendimento público de teste',notes:'Observação de teste',has_pending_issue:true,requires_return:true});
  await request('POST','/api/visits/'+id+'/departments/'+item.id+'/complete');
  await request('POST','/api/visits/'+id+'/finish');
  const sent=await request('POST','/api/visits/'+id+'/departments/'+item.id+'/request-validation',{selected_contact_id:1});
  const url='/api/visits/public/validate/'+tokenFrom(sent);
  const detail=await request('GET',url);
  assert.equal(detail.status,200);
  for(const key of ['visit_created_at','visit_started_at','visit_finished_at','started_at','completed_at'])assert.ok(detail.body[key]);
  assert.equal(detail.body.activities,'Atendimento público de teste');
  assert.equal(detail.body.notes,'Observação de teste');
  assert.equal(detail.body.has_pending_issue,1);assert.equal(detail.body.requires_return,1);
  assert.equal(detail.body.responsible_name,'Gestor');
  for(const key of ['token_hash','recipient_email','contact_id'])assert.equal(detail.body[key],undefined);
  assert.equal((await request('POST',url,{accepted:false,name:detail.body.responsible_name})).status,400);
  const confirmed=await request('POST',url,{accepted:true,name:detail.body.responsible_name});
  assert.equal(confirmed.status,200);assert.equal(confirmed.body.protocol,sent.body.protocol);
  assert.equal((await request('GET',url)).status,409);
  assert.equal((await request('POST',url,{accepted:true,name:'Gestor'})).status,409);
  assert.equal((await request('GET','/api/visits/public/validate/invalid-token')).status,404);
});
test.before(async()=>{tempDir=fs.mkdtempSync(path.join(os.tmpdir(),'goldtech-validation-'));db=new sqlite3.Database(path.join(tempDir,'test.sqlite'));await exec("PRAGMA foreign_keys=ON;CREATE TABLE companies(id INTEGER PRIMARY KEY,name TEXT NOT NULL);CREATE TABLE users(id INTEGER PRIMARY KEY,name TEXT NOT NULL,role TEXT NOT NULL,active INTEGER NOT NULL);CREATE TABLE tickets(id INTEGER PRIMARY KEY);INSERT INTO companies VALUES(1,'Cliente'),(2,'Outra empresa');INSERT INTO users VALUES(1,'Tecnico','tecnico',1);"+migration.up+contactScopeMigration.up+"INSERT INTO company_departments(id,company_id,name) VALUES(1,1,'TI'),(2,1,'Financeiro'),(3,2,'TI');INSERT INTO company_contacts(id,company_id,department_id,contact_type,name,email,job_title) VALUES(1,1,1,'primary_manager','Gestor','gestor@example.com','Diretor'),(2,1,2,'substitute','Substituto','sub@example.com','Coordenador'),(3,2,3,'primary_manager','Outro','outro@example.com','Diretor');");const app=express();app.use(express.json());const options={mailer:{sendMail:async message=>messages.push(message)},frontendUrl:'http://frontend.test'};visits(app,db,options);validations(app,db,options);await new Promise(resolve=>{server=app.listen(0,'127.0.0.1',resolve)});baseUrl='http://127.0.0.1:'+server.address().port;visit=(await request('POST','/api/visits',{company_id:1,technician_id:1,department_ids:[1,2]})).body;await exec("INSERT INTO company_contacts(company_id,department_id,contact_type,name,email,job_title) VALUES(1,2,'primary_manager','Gestor Financeiro','financeiro@example.com','Diretor')");await request('POST','/api/visits/'+visit.id+'/start');for(const [index,item] of visit.departments.entries()){await request('PUT','/api/visits/'+visit.id+'/departments/'+item.id,{demand_status:'sem_demanda'});await request('POST','/api/visits/'+visit.id+'/departments/'+item.id+'/complete');await request('POST','/api/visits/'+visit.id+'/departments/'+item.id+'/request-validation',{selected_contact_id:index?2:1})}assert.equal(messages.length,0);await request('POST','/api/visits/'+visit.id+'/finish');assert.equal(messages.length,2);});
test.after(async()=>{await new Promise(resolve=>server.close(resolve));await new Promise((resolve,reject)=>db.close(error=>error?reject(error):resolve()));fs.rmSync(tempDir,{recursive:true,force:true})});
test('rejeita contato de outra empresa ou setor na validação',async()=>{const item=visit.departments[0];const url='/api/visits/'+visit.id+'/departments/'+item.id+'/request-validation';assert.equal((await request('POST',url,{selected_contact_id:2})).status,409);assert.equal((await request('POST',url,{selected_contact_id:3})).status,409)});
test('gera token forte para gestor do setor, guarda apenas hash e GET público mínimo',async()=>{const item=visit.departments[0];const result=await request('POST','/api/visits/'+visit.id+'/departments/'+item.id+'/request-validation',{selected_contact_id:1});assert.equal(result.status,201);assert.equal(messages.at(-1).to,'gestor@example.com');tokens.manager=tokenFrom(result);assert.ok(tokens.manager.length>=43);const stored=await get('SELECT token_hash,sent_at,status FROM visit_validation_requests WHERE protocol=?',[result.body.protocol]);assert.notEqual(stored.token_hash,tokens.manager);assert.equal(stored.token_hash,validations.tokenHash(tokens.manager));assert.ok(stored.sent_at);assert.equal(stored.status,'sent');const publicData=await request('GET','/api/visits/public/validate/'+tokens.manager);assert.equal(publicData.status,200);assert.equal(publicData.body.department_name,'TI');assert.equal(publicData.body.responsible_name,'Gestor');assert.equal(publicData.body.recipient_email,undefined)});
test('valida parcialmente com aceite, registra evidências e bloqueia reutilização',async()=>{assert.equal((await request('POST','/api/visits/public/validate/'+tokens.manager,{name:'Gestor',role:'Diretor',accepted:false})).status,400);const validated=await request('POST','/api/visits/public/validate/'+tokens.manager,{name:'Gestor Confirmador',role:'Diretor',accepted:true},{'User-Agent':'validation-test'});assert.equal(validated.status,200);assert.equal(validated.body.visit_validated,false);const row=await get('SELECT status,accepted,validated_at,validation_ip,validation_user_agent FROM visit_validation_requests WHERE token_hash=?',[validations.tokenHash(tokens.manager)]);assert.equal(row.status,'validated');assert.equal(row.accepted,1);assert.ok(row.validated_at);assert.ok(row.validation_ip);assert.equal(row.validation_user_agent,'validation-test');assert.equal((await request('POST','/api/visits/public/validate/'+tokens.manager,{name:'Novo',accepted:true})).status,409);assert.equal((await get('SELECT status FROM technical_visits WHERE id=?',[visit.id])).status,'awaiting_validation')});
test('substituto recebe e reenvio revoga token anterior',async()=>{const item=visit.departments[1];const first=await request('POST','/api/visits/'+visit.id+'/departments/'+item.id+'/request-validation',{selected_contact_id:2});assert.equal(first.status,201);assert.equal(messages.at(-1).to,'sub@example.com');const oldToken=tokenFrom(first);const second=await request('POST','/api/visits/'+visit.id+'/departments/'+item.id+'/request-validation',{selected_contact_id:2});assert.equal(second.status,201);tokens.substitute=tokenFrom(second);assert.equal((await request('GET','/api/visits/public/validate/'+oldToken)).status,410);assert.equal((await get('SELECT status FROM visit_validation_requests WHERE token_hash=?',[validations.tokenHash(oldToken)])).status,'revoked')});
test('token expirado é recusado',async()=>{await exec("UPDATE visit_validation_requests SET expires_at='2000-01-01 00:00:00' WHERE token_hash='"+validations.tokenHash(tokens.substitute)+"'");assert.equal((await request('GET','/api/visits/public/validate/'+tokens.substitute)).status,410);assert.equal((await get('SELECT status FROM visit_validation_requests WHERE token_hash=?',[validations.tokenHash(tokens.substitute)])).status,'expired');const item=visit.departments[1];const fresh=await request('POST','/api/visits/'+visit.id+'/departments/'+item.id+'/request-validation',{selected_contact_id:2});tokens.substitute=tokenFrom(fresh)});
test('último setor validado conclui a validação da visita e registra auditoria',async()=>{const result=await request('POST','/api/visits/public/validate/'+tokens.substitute,{name:'Substituto',role:'Coordenador',accepted:true});assert.equal(result.status,200);assert.equal(result.body.visit_validated,true);const final=await get('SELECT status,validated_at FROM technical_visits WHERE id=?',[visit.id]);assert.equal(final.status,'validated');assert.ok(final.validated_at);const events=await get("SELECT COUNT(*) AS count FROM visit_audit_events WHERE visit_id=? AND event_type IN ('validation_requested','department_validated','visit_validated')",[visit.id]);assert.ok(events.count>=6)});
