const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('fs');const os=require('os');const path=require('path');
const express=require('express');const sqlite3=require('sqlite3').verbose();
const migration=require('../migrations/001_create_visits_schema');
const contactScopeMigration=require('../migrations/002_scope_company_contacts_by_department');
const visits=require('../routes/visits');
let db,server,baseUrl,tempDir,visit;
const exec=sql=>new Promise((resolve,reject)=>db.exec(sql,error=>error?reject(error):resolve()));
const all=(sql,params=[])=>new Promise((resolve,reject)=>db.all(sql,params,(error,rows)=>error?reject(error):resolve(rows)));
async function request(method,url,body){const response=await fetch(baseUrl+url,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});return{status:response.status,body:await response.json()}}
test.before(async()=>{tempDir=fs.mkdtempSync(path.join(os.tmpdir(),'goldtech-flow-'));db=new sqlite3.Database(path.join(tempDir,'test.sqlite'));await exec("PRAGMA foreign_keys=ON;CREATE TABLE companies(id INTEGER PRIMARY KEY,name TEXT NOT NULL);CREATE TABLE users(id INTEGER PRIMARY KEY,name TEXT NOT NULL,role TEXT NOT NULL,active INTEGER NOT NULL);CREATE TABLE tickets(id INTEGER PRIMARY KEY);INSERT INTO companies VALUES(1,'Cliente');INSERT INTO users VALUES(1,'Tecnico','tecnico',1);"+migration.up+contactScopeMigration.up);const app=express();app.use(express.json());visits(app,db);await new Promise(resolve=>{server=app.listen(0,'127.0.0.1',resolve)});baseUrl='http://127.0.0.1:'+server.address().port;});
test.after(async()=>{await new Promise(resolve=>server.close(resolve));await new Promise((resolve,reject)=>db.close(error=>error?reject(error):resolve()));fs.rmSync(tempDir,{recursive:true,force:true});});
test('cria visita com empresa, técnico, unidade e setores',async()=>{await exec("INSERT INTO company_units(company_id,name) VALUES(1,'Matriz');INSERT INTO company_departments(company_id,unit_id,name) VALUES(1,1,'TI'),(1,1,'Financeiro');");const result=await request('POST','/api/visits',{company_id:1,unit_id:1,technician_id:1,visit_type:'preventive',department_ids:[1,2],started_at:'2020-01-01'});assert.equal(result.status,400);const created=await request('POST','/api/visits',{company_id:1,unit_id:1,technician_id:1,visit_type:'preventive',department_ids:[1,2]});assert.equal(created.status,201);assert.match(created.body.visit_number,/^VIS-/);assert.equal(created.body.departments.length,2);assert.equal(created.body.started_at,null);const listed=await request('GET','/api/visits');assert.equal(listed.status,200);assert.equal(listed.body.length,1);const detail=await request('GET','/api/visits/'+created.body.id);assert.equal(detail.status,200);assert.equal(detail.body.departments.length,2);visit=created.body;});
test('exige principal por setor, aceita substituto opcional e gera horário no servidor',async()=>{assert.equal((await request('POST','/api/visits/'+visit.id+'/start')).status,409);await exec("INSERT INTO company_contacts(company_id,department_id,contact_type,name,email,job_title) VALUES(1,1,'primary_manager','Gestor TI','ti@example.com','Gestor'),(1,2,'primary_manager','Gestor Financeiro','financeiro@example.com','Gestor');");const started=await request('POST','/api/visits/'+visit.id+'/start');assert.equal(started.status,200);assert.equal(started.body.status,'in_progress');assert.ok(started.body.started_at);visit=started.body;});
test('registra setor com demanda e horário automático',async()=>{const item=visit.departments[0];const updated=await request('PUT','/api/visits/'+visit.id+'/departments/'+item.id,{demand_status:'com_demanda',activities:'Atualização executada',notes:'OK',has_pending_issue:true,requires_return:false});assert.equal(updated.status,200);assert.equal(updated.body.activities,'Atualização executada');assert.equal(updated.body.has_pending_issue,1);assert.ok(updated.body.started_at);const completed=await request('POST','/api/visits/'+visit.id+'/departments/'+item.id+'/complete');assert.equal(completed.status,200);assert.ok(completed.body.completed_at);assert.equal(completed.body.validation_status,'not_requested');});
test('setor sem demanda rejeita texto e gera descrição automática',async()=>{const item=visit.departments[1];assert.equal((await request('PUT','/api/visits/'+visit.id+'/departments/'+item.id,{demand_status:'sem_demanda',activities:'texto manual'})).status,400);const updated=await request('PUT','/api/visits/'+visit.id+'/departments/'+item.id,{demand_status:'sem_demanda'});assert.equal(updated.status,200);assert.equal(updated.body.activities,null);assert.equal(updated.body.standardized_description,visits.NO_DEMAND_DESCRIPTION);assert.ok(updated.body.started_at);});
test('bloqueia finalização incompleta e finaliza após todos os setores',async()=>{assert.equal((await request('POST','/api/visits/'+visit.id+'/finish')).status,409);const item=visit.departments[1];assert.equal((await request('POST','/api/visits/'+visit.id+'/departments/'+item.id+'/complete')).status,200);const finished=await request('POST','/api/visits/'+visit.id+'/finish');assert.equal(finished.status,200);assert.equal(finished.body.status,'awaiting_validation');assert.ok(finished.body.finished_at);assert.equal(finished.body.validated_at,null);const events=await all('SELECT event_type FROM visit_audit_events WHERE visit_id=? ORDER BY id',[visit.id]);for(const required of ['visit_created','visit_started','department_completed','visit_finished'])assert.ok(events.some(event=>event.event_type===required),required+' ausente');});
